version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports: 
      - "443:443"
    volumes: 
      - ./srcs/requirements/nginx/conf/:/etc/nginx/http.d/
      - ./srcs/requirements/nginx/tools:/etc/nginx/ssl/
      - ./${USER}/data_ngnix/public/html:/var/www/
    restart: always
#    depends_on: 
#      - wordpress