#file specifico www
[www]
#definisco utente default per eseguire i processi PHP
user = www-data
#utente default per specificare il gruppo di sistema PHP-FPM
group = www-data
#wordpress nome host porta 9000 porta su cui PHP ascolta la richiesta
listen = wordpress:9000
#la proprieta del socket diventa dell'utente
listen.owner = www.data
#il numero di processi viene regolato dinamicamente in base ai processi
pm = dynamic
#masimo numero id prcessi
pm.max_children = 5
#numero di processi da avviare automaticamente all'avvio
pm.start.servers = 2
#numero minimo e massimo di processi pronti a rispndere alle richiese
pm.min_spare_server = 1
pm.max_spare_server = 3
#inpedisce a PHP di cancellare le variabili d'ambiente
clear_env = no