server
{
#creo un blocco server che ascolta le connessioni HTTPS ipv6 e non
    listen 443 ssl;
    listen [::]:443 ssl;
#il server rispndera all'indirizzo (sgalli.42.fr www.sgalli.42.fr)
    server_name sgalli.42.fr www.sgalli.42.fr;

#specifico i percosi per il certificato e chiave ssl le vesioni accettate
    ssl_certificate     /etc/ssl/cert.cert;
    ssl_certificate_key /etc/ssl/key.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

#definisco la directori radice per i file che verranno serviti
    root /var/www/wordpress;

#definisco un indice chiamato index.php e li gestisco con il blocco location che risponde a tutti i file cher terminano con .php
    index index.php;
#se esiste lo inoltra altimenti lo manda a index.php
    location /
    {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$
    {
#divido il file in file stesso e informazioni del percorso aggiuntivo
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
#inoltro la richiesta al server PHP-FPM che ascolta alla poprta 9000
        fastcgi_pass wordpress:9000;
#l'indice per le richieste fastCGI diventa index php
        fastcgi_index index.php;
#includo i parametri predefiniti fastcgi
        include fastcgi_params;
#imposto la variabile script_filename per sapere quale sript eseguire
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#impsto la variabile PATH_INFO che contiene informazioni per lo script PHP
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}